# Default values for gitlab-mr-reminder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
schedule:
config:
  GITLAB_DOMAIN: "xxx"
  GITLAB_TOKEN: "xxx"
  GITLAB_GROUP_NAME: "team"
  SLACK_WEBHOOK: "https://hooks.slack.com/services/xxx"
  SLACK_CHANNEL: "#xxx"