name: gitlab-mr-reminder build
on:
  push:
    branches: [ master ]
    paths:
      - 'src/*'
      - Dockerfile
      - '.github/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: setup buildx
          uses: docker/setup-buildx-action@v1
        - name: login
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: emdupp/gitlab-mr-reminder:latest